
version: 2

jobs:
  build:
    steps:
      - checkout
      - run:
          name: Setup Env
          command: |
            echo 'export TAG=0.1.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
            echo 'export IMAGE_NAME=pnode_circle' >> $BASH_ENV
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build and push Docker image
          command: |
            docker build -t hoangphu98/$IMAGE_NAME:$TAG ./js/
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push hoangphu98/$IMAGE_NAME:$TAG